# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Project.create(word: '茨城')
Project.create(word: '群馬')
Project.create(word: '埼玉')
Project.create(word: '東京')
Project.create(word: '群馬')
Project.create(word: '千葉')
Project.create(word: '神奈川')
Project.create(word: '長野')
Project.create(word: '山梨')
Project.create(word: '静岡')
Project.create(word: '愛知')
Project.create(word: '岐阜')
Project.create(word: '富山')
Project.create(word: '石川')
Project.create(word: '福井スイートルーム')
Project.create(word: '滋賀旅館')
Project.create(word: '三重スーパーホテル')
Project.create(word: '京都ホテル')
Project.create(word: '奈良公園')
Project.create(word: '大阪城')
Project.create(word: '和歌山ルーム')
Project.create(word: '兵庫旅館')
Project.create(word: '鳥取スーパーホテル')
Project.create(word: '岡山グランドホテル')
Project.create(word: '島根グランドホテル')
Project.create(word: '広島スーパーホテル')
Project.create(word: '山口旅館')
Project.create(word: '香川ホテル')
Project.create(word: '徳島温泉')
Project.create(word: '高知旅館')
Project.create(word: '愛媛スイートルーム')
Project.create(word: '福岡グランドホテル')
Project.create(word: '大分スーパーホテル')
Project.create(word: '宮崎帝国ホテル')
Project.create(word: '鹿児島')
Project.create(word: '熊本旅館')
Project.create(word: '佐賀グランドホテル')
Project.create(word: '長崎ホテル')
Project.create(word: "沖縄帝国ホテル")
Project.create(word: "沖縄プリンスホテル")
